Ming's obviously better game of pong compared to a certain someone's …
minghz/live_playground pull request #3
Opened 2019-04-20 06:13 UTC by minghz

…game of pong

😉

2019-04-20 13:26 UTC, DonCarnohan commented
In 100% seriousness I see a few flaws, 
1. That score bug I mentioned in discord is still a thing, it seemed like when the ball hit a corner perfectly the score went up by 3... I was able to reproduce it just by playing the game and not hitting the ball for a while, watch the score

2. Your ball will always be traveling at a perfect 45 degree angle, It makes the game a bit flat, you should be able to start with the ball at a higher y speed than x to give it a little more difficulty

3. The paddles control a bit weird (As you know) relying on the repeat rate of your keyboard settings, which also results in a delay immediately after pressing the direction.z Also with the way it's handled they move a bit jittery, whereas the ball is buttery smooth.

4. The bounce logic seems a bit flawed, though I can't quite break down what is happening. Looking at the code it seems like if the ball enters the side of the paddle before hitting the back of the board it will still bounce anyway, but I can't confirm if that's what's happening here. (see the video I sent you in discord). 775 and 21 don't seem like they're related, though they're the values you use to determine if a ball bounces... see next point for more complaining there.

5. Your board size is fixed!?!? I see hard coded values for the board height and it makes me want to cry Ming... Oh man, so many hard coded values like paddle size and ball size! This is actually pretty bad because the logic for subtracting them from the bounce locations and what not isn't written in, so if I wanted to update this to be a bigger board I'd need to do all the math and update these values.

6. I'm seeing a decent amount of repeated code which could have probably leveraged some language features to keep things a bit more DRY.

7. (me nit-picking) If I hold up and down at the same time the paddles jitter.

Overall the code is much simpler than mine though, but likely due to some hardcoded values and some slightly more fixed values, try pulling the paddles away from the walls a bit and I think you'll see your bounce logic is flawed, the ball shouldn't bounce off the paddle if it's already behind the paddle.

Your turn to rip mine to shreds! ⚔️

2019-04-20 13:27 UTC, DonCarnohan requested changes
lib/demo_web/live/pong_two_live.ex:14 seems to have some sort of grammatical or spelling error. It appears you wrote "inferior" incorrectly

2019-04-20 20:22 UTC, minghz commented
> In 100% seriousness I see a few flaws,
> 
>     1. That score bug I mentioned in discord is still a thing, it seemed like when the ball hit a corner perfectly the score went up by 3... I was able to reproduce it just by playing the game and not hitting the ball for a while, watch the score
> 
>     2. Your ball will always be traveling at a perfect 45 degree angle, It makes the game a bit flat, you should be able to start with the ball at a higher y speed than x to give it a little more difficulty
> 
>     3. The paddles control a bit weird (As you know) relying on the repeat rate of your keyboard settings, which also results in a delay immediately after pressing the direction.z Also with the way it's handled they move a bit jittery, whereas the ball is buttery smooth.
> 
>     4. The bounce logic seems a bit flawed, though I can't quite break down what is happening. Looking at the code it seems like if the ball enters the side of the paddle before hitting the back of the board it will still bounce anyway, but I can't confirm if that's what's happening here. (see the video I sent you in discord). 775 and 21 don't seem like they're related, though they're the values you use to determine if a ball bounces... see next point for more complaining there.
> 
>     5. Your board size is fixed!?!? I see hard coded values for the board height and it makes me want to cry Ming... Oh man, so many hard coded values like paddle size and ball size! This is actually pretty bad because the logic for subtracting them from the bounce locations and what not isn't written in, so if I wanted to update this to be a bigger board I'd need to do all the math and update these values.
> 
>     6. I'm seeing a decent amount of repeated code which could have probably leveraged some language features to keep things a bit more DRY.
> 
>     7. (me nit-picking) If I hold up and down at the same time the paddles jitter.
> 
> 
> Overall the code is much simpler than mine though, but likely due to some hardcoded values and some slightly more fixed values, try pulling the paddles away from the walls a bit and I think you'll see your bounce logic is flawed, the ball shouldn't bounce off the paddle if it's already behind the paddle.
> 
> Your turn to rip mine to shreds! ⚔️

Aye, I found out the problem with the score bug. Basically, my bounce conditionals relied on the `<=` and `>=` operators, AND the side-wall bounce conditional came before the back-wall bounce. This caused the ball to bounce INTO the back wall whenever a perfect corner hit happened, and it would take 3 ticks before it would move away from the "score counting zone".

All I did to fix it is to account for those perfect corner hits (both wall-on-wall and wall-on-paddle), and have the ball bounce 180 degrees back. And of course, just clearing up the actual size of my board. I think the CSS property for the border screwed up some other numbers down the line. Also, my colliders for the ball were all relying on the center coordinate, not the perimeter.

I don't quite mind the 45 degree, but I changed it a little to increase the Y speed. Luckly the X and Y speeds are in a constant, and its relatively simple to change.

Yes, the board size is fixed 8D That's specifically because I wanted to make you cry.
Naw, I just thought it would be over-engineering.

Not sure what to do with the Paddle smoothness yet. `phx-keydown` and `keyup` seem like the only supported events? I'm not sure if they have something that just checks if the key is already down 🤷‍♀️ Or I would have to do some custom JS on that, which is something I would want to avoid.

The other thing I could do is check key status every tick. That would bring the paddle movements into the game clock, which is fine, but I specifically didn't at the beginning because I wanted to make it a special snowflake of asynchronicity.

2019-04-22 20:49 UTC, DonCarnohan approved these changes

2019-04-22 20:52 UTC, merged